# Generated by Django 5.0.4 on 2024-05-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('ply_height', models.IntegerField()),
                ('cutting_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='cuttingcal.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cuttingcal.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_set', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cuttingcal.project')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cuttingcal.style')),
            ],
        ),
        migrations.CreateModel(
            name='StyleFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_comp', models.CharField(choices=[('A', 'Fabric A'), ('B', 'Fabric B'), ('C', 'Fabric C'), ('D', 'Fabric D')], max_length=1)),
                ('perimeter', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=100)),
                ('fabric_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_styles', to='cuttingcal.fabric')),
                ('fabric_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_styles_weight', to='cuttingcal.fabric')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_fabrics', to='cuttingcal.style')),
            ],
        ),
    ]
