# Generated by Django 5.0.4 on 2024-05-22 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0002_customer_fabric_style_factory_project_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylefabric',
            old_name='fabric_name',
            new_name='fabric',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size_set',
        ),
        migrations.RemoveField(
            model_name='stylefabric',
            name='fabric_weight',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=2)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cuttingcal.order')),
            ],
        ),
    ]
