# Generated by Django 5.0.4 on 2024-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0004_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylefabric',
            name='code',
        ),
        migrations.AddField(
            model_name='size',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='code',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
