# Generated by Django 5.0.4 on 2024-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0005_remove_stylefabric_code_size_qty_alter_fabric_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylefabric',
            name='avg_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stylefabric',
            name='perimeter',
            field=models.IntegerField(null=True),
        ),
    ]
