# Generated by Django 5.0.6 on 2024-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0009_rename_fabric_stylefabric_fabric_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
