# Generated by Django 5.0.6 on 2024-07-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0010_order_qty_delete_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylefabric',
            name='fabric_code',
        ),
    ]
