# Generated by Django 5.0.6 on 2024-08-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0011_remove_stylefabric_fabric_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stylefabric',
            old_name='fabric_comp',
            new_name='material_comp',
        ),
        migrations.AddField(
            model_name='stylefabric',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_fabrics', to='cuttingcal.fabric'),
        ),
        migrations.AlterField(
            model_name='stylefabric',
            name='avg_consumption',
            field=models.IntegerField(default='10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stylefabric',
            name='perimeter',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cuttingcal.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cuttingcal.project'),
        ),
    ]
