# Generated by Django 5.0.6 on 2024-08-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0012_rename_type_fabric_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylefabric',
            name='avg_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stylefabric',
            name='perimeter',
            field=models.IntegerField(null=True),
        ),
    ]
