# Generated by Django 5.0.6 on 2024-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttingcal', '0013_alter_stylefabric_avg_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='style_img',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
